### ISSUE TITLE
Transcription popup should not block Annotation markers

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/scribes-of-the-cairo-geniza#101]
## UI needs improvement
When the Transcription popup appears - after a user places a start and an end marker indicating a line of text - it should NOT block the Annotation markers that were just created.

Requested solution: the transcription popup should appear vertically below or beneath the start and end markers. (Note: it should be safe to assume all lines of text are horizontal... but someone correct me if I'm wrong.)

Thought: what if the user adds start/end markers at a line of text... that appears at the bottom of the browser window? (Metathought: apply maximum vertical offsets for the Transcription popup appearing; i.e. it can't appear so far at the "bottom" of a browser window that it effectively disappears from view.)

Thought: should a similar repositioning code apply when a Transcription popup appears after selecting an existing Annotation?

### Status
This is last remaining issue from Issue #92 "Full Launch Checklist", as it's not a trivial fix.

**Comment by shaunanoordin** [comment]
It seems that best point to start with here is to use `react-rnd`'s `default` attribute: https://www.npmjs.com/package/react-rnd

I'm guessing we'll need to insert the `default.x` and `default.y` values to calls of `toggleAnnotation(<SelectedAnnotation />, dimensions)` within `SubjectViewer.jsx`

Alright, this might get a bit trippy, but I CHOOSE YOU, GIT-ISSUE. Assigning myself to this.

**Comment by wgranger** [comment]
Closed by #107
