### ISSUE TITLE
Add IMLS logo to front page; turn all logos into clickable links

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#104]
This issue notes the need to 1) add the IMLS logo to the front page, and 2) change all logos to clickable links, as is the case with the logos on [Anti-Slavery Manuscripts](https://www.antislaverymanuscripts.org/).

Zooniverse: https://www.zooniverse.org/

Penn Libraries: http://www.library.upenn.edu/

JTS: http://www.jtsa.edu/

Princeton: https://www.princeton.edu/~geniza/

Cambridge: http://www.lib.cam.ac.uk/collections/departments/taylor-schechter-genizah-research-unit

Manchester: http://www.library.manchester.ac.uk/rylands/

Bodleian: https://www.bodleian.ox.ac.uk/

Centre for Interdisciplinary Research at Haifa: http://gniza.haifa.ac.il

e-Lijah lab: (don't seem to have a web site -- I'll reach out to Moshe)

IMLS: add logo (can d/l [here](https://www.imls.gov/grants/manage-your-award/grantee-communications-kit/imls-logos)); https://www.imls.gov/
Note: IMLS logo can go on a new row under current logos, centered, if necessary (we don't want to make any of the logos smaller)

**Comment by shaunanoordin** [comment]
On it 👌

**Comment by snblickhan** [comment]
Oops - sorry for the confusion @shaunanoordin. I think just the home page will be ok.

**Comment by shaunanoordin** [comment]
Noice, thanks Sam! OK, the PR will be ready in five minutes.
