### ISSUE TITLE
Add missing character (alef lamed) to keyboards 

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#113]
Alef Lamed (a combination of the alef and lamed characters) appears on the crib sheets. However, it does not appear on the keyboards. Penn have requested that this character be added to the keyboard in place where the period key would usually be found.

Square
- [ ] Oriental NE - https://upenn.box.com/s/jh1p4tto0g5nm5ntq7d8fcdmdss4q9r6
- [ ] Sephardi - https://upenn.box.com/s/txn7p081lmygh1rxxcpxcnla3ontrkm8
- [ ] Yemenite - https://upenn.box.com/s/mmvq9r93sbbcq41flw7sptc9o3mzzsqn 

Minuscule
- [ ] Ashkenazi - https://upenn.box.com/s/sxd5bvuw8i5ukm9rq3ggrau4dqrchkez
- [ ] Oriental NE - https://upenn.box.com/s/z0m1rrxrrorlenkv54ab4a8wq4bz4myo
- [ ] Yemenite - https://upenn.box.com/s/8by2dwdbyhcqbdmxcji827rpsjduy0w1

Cursive
- [ ] Italian -https://upenn.box.com/s/qlm957phrh1i8lwofrf699jrpblr8iqk
- [ ] Maghrebi -  https://upenn.box.com/s/og6yvba6t0p61xwz387nk1jqg790yudm
- [ ] Oriental SW - https://upenn.box.com/s/mapd02rmxxeodzlkzmok27vg5gx2jsf
- [ ] Sephardi - https://upenn.box.com/s/gpme7aifxhx5319mbsaefoj75w5m9pjm

**Comment by wgranger** [comment]
Are we sure we want to put it where the period is usually found? On standard Hebrew keyboards, that space is reserved for the final tadi. I don't think removing it is a good idea. Perhaps alef lamed should take the question mark location?

**Comment by snblickhan** [comment]
Yes, question mark location.

**Comment by wgranger** [comment]
Ok. For the script keyboards where it doesn't exist, I'm going to show the modern equivalent (rather than hiding it completely).
