### ISSUE TITLE
Edit text for Text Modifier help modal

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#117]
Current text: ![example](http://i64.tinypic.com/zjxjzb.png)

New text:

Use these markers to indicate special occurrences within the text:	
**Insertion** For text that has been added in. _[תוספת]Inserted Text Here[/תוספת]_
**Deletion** For text that has been crossed out. _[מחיקה]Deleted Text Here[/מחיקה]_
**Damaged** For text that is obscured or destroyed due to physical damage or wear & tear. _Transcribe Until The Damage [פגום] Then Continue After_
**Drawing** To mark drawings that interrupt lines of text. _Transcribe Until Drawing [ציור] Then Continue_
**Grid** To indicate tabular text. _[טבלה/שרטוט]Tabular Text Here[/טבלה/שרטוט]_
**Divine Name** To use in place of the Divine Name. _Transcribe Until Name [ה’] Then Continue_

**Comment by wgranger** [comment]
Wait until #114 has been merged to address this as some changes in that PR will affect how this should be addressed.
