### ISSUE TITLE
Add Arabic translations

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#128]
All Arabic (& Hebrew) translations available [here](https://docs.google.com/document/d/13we_9qPoZiKOKdIOaTtcYD4ZnINPFvr6AelMMNoxFwI/edit?usp=sharing).

Hebrew translations are okay for now, but if any Hebrew translation is missing from the CFE, feel free to add it from the Google doc.

**Comment by wgranger** [comment]
We are still missing Hebrew translations from [this document](https://docs.google.com/document/d/1rb-PZodD5wwaNTX6fB6uzndA8fk0pB6Hgb5XjQF6J70/edit)
