### ISSUE TITLE
Return to Classify from Talk

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#168]
Is there any way to change the URL of the "Classify" tab when accessed through PFE? Currently, if someone is classifying on the CFE and goes to the Talk boards, clicking "Classify" from the Talk page takes them to the PFE workflow (https://www.zooniverse.org/projects/judaicadh/scribes-of-the-cairo-geniza/classify) rather than back to what they were working on. 

Ideal fix: Classify button goes to the last workflow a volunteer was working on.
MVP fix: Classify button goes to the .org or the "Choose a workflow" page.

**Comment by srallen** [comment]
Should anyone be able to classify on the PFE classifier page?

**Comment by srallen** [comment]
If not, there can be a project redirect like we do for other CFEs, like https://www.zooniverse.org/projects/zooniverse/chimp-and-see/

**Comment by snblickhan** [comment]
Yes, the PFE workflow is still active, so we'll want it to remain an option.

**Comment by srallen** [comment]
We don't support conditional redirects like that unfortunately.

**Comment by snblickhan** [comment]
Yeah, that's why I noted the ideal v MVP fix options -- I feel like it would be better to redirect to the CFE, as the "choose a workflow" prompt will appear: https://www.scribesofthecairogeniza.org/classify

**Comment by snblickhan** [comment]
(the PFE workflow is on that list, too, so it's an extra click for some folks but at least all the options are there)

**Comment by srallen** [comment]
Ok, that clarifies it, thanks. It might work with the project level redirect.

**Comment by snblickhan** [comment]
Similar problem that needs to be updated: when you search from Zooniverse.org/projects, the link goes to the Project Builder site instead of the CFE.

**Comment by eatyourgreens** [comment]
You should be able to fix that by adding a redirect on the project’s admin page.

**Comment by snblickhan** [comment]
Done. Thanks, Jim!

**Comment by snblickhan** [comment]
Looks like the talk menu is redirecting to scribesofthecairogeniza.org/classify, and search bar is now going to scribesofthecairogeniza.org, so this all seems sorted. I'll close the issue unless someone says otherwise.
