### ISSUE TITLE
Notes on design

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/scribes-of-the-cairo-geniza#17]
A few small updates (also changed on the InVision prototype) ✌️ 

## Home
- [x] Remove `Scroll down` link from top section
- [x] Changed Princeton Geniza Project to Princeton Geniza Lab – just need to update the SVG (downloadable via Inspect mode in InVision)
- [ ] Partner institutions will be split into two sections, Partner vs Contributing (design to come)
- [x] New photo for about section (to come)

**Comment by wgranger** [comment]
Are we still doing this split between partner vs. contributing, or is this pretty much taken care of with the way the site looks now with provenance vs. research partners?
