### ISSUE TITLE
Update url-regex / Update Webpack

### ISSUE THREAD

**Issue by wgranger** [zooniverse/scribes-of-the-cairo-geniza#187]
It's a bit peculiar we got a security advisory since this repo isn't using url-regex directly. There is a package being used way down in the `package-lock.json` called css-url-regex, which eventually derives from `image-webpack-loader`. Knowing that, a webpack update will probably take care of this issue.

[Original advisory](https://github.com/advisories/GHSA-v4rh-8p82-6h5w)

**Comment by shaunanoordin** [comment]
After the security update patch in #193, I don't see `url-regex` anywhere in package-lock.json - it might have been fixed in that PR or an earlier update patch. So, that's good, I think? That's good, I think! 👌
