### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/scribes-of-the-cairo-geniza#294]
Images like the workflow diagram and team images imported with `require` don't appear to be working on staging - https://scribes.preview.zooniverse.org/about

**Comment by eatyourgreens** [comment]
The last big change to the image loader was #227, which bumped it from version 4 to version 8. The file paths might need updating for the new version. I’m not sure.

**Comment by eatyourgreens** [comment]
Imported images do show up so the fix could be to replace `require` with `import`.

**Comment by eatyourgreens** [comment]
eg. https://github.com/zooniverse/scribes-of-the-cairo-geniza/commit/61c35c43fae49569b3d2ae407af60da7e120672e added a bunch of images that use `import` instead of `require`. Sadly, the commit history doesn’t tell us why, but I think those images are loaded on staging.

**Comment by eatyourgreens** [comment]
Here's one of the broken image URLs. The entire exported object is being written to the URL, rather than the default export.
`https://scribes.preview.zooniverse.org/[object Module]`
