### ISSUE TITLE
Accessibility Notes

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/scribes-of-the-cairo-geniza#4]
## Accessibility Notes
I'm keeping a thread open for keeping track of Accessibility-related resources, documents, notes, reminders, etc for Scribes of the Cairo Geniza. This can be made compatible with [ASM](github.com/zooniverse/anti-slavery-manuscripts) as well, of course.

Pinging @beckyrother for her design insights. Everyone on the team: feel free to update this.

### Resources
- Keyboard controls for accessibility: https://webaim.org/techniques/keyboard/

### Questions
- [ ] Which keyboard shortcuts are 'safe' to use across all browsers across all OSes? (c.f. that time we tried Ctrl+N to navigate in ASM, but that opened new browser windows on Chrome+Win10)

**Comment by eatyourgreens** [comment]
This is a comprehensive list of [browser shortcuts on Windows](http://dmcritchie.mvps.org/firefox/keyboard.htm).

**Comment by eatyourgreens** [comment]
Good advice would be to take advantage of event bubbling, attach listeners only to the DOM elements that need them and avoid adding keyboard listeners at the window or document level.

**Comment by beckyrother** [comment]
Thanks Shaun! 
Here's how Gmail does it, which is a similar use case to ours in that they both have type entries. I'd trust that they've done some extensive testing before implementing. 

<img width="942" alt="inbox_ _becky_j_rother_gmail_com" src="https://user-images.githubusercontent.com/1392130/33766333-efac4ed6-dc14-11e7-97da-bd0ae6b17c69.png">
