### ISSUE TITLE
Account for Right to Left Tutorial Steps

### ISSUE THREAD

**Issue by wgranger** [zooniverse/scribes-of-the-cairo-geniza#51]
When switching to Hebrew or Arabic, the tutorial should start on the right and advance to the left.

**Comment by shaunanoordin** [comment]
This has been resolved, but I'm not sure which PR took care of the RtL changes for the tutorials, Field Guide, and the `<StepThrough>` components.

**Comment by wgranger** [comment]
The original PR that introduced tutorials should've fixed this. This was left open because although the controls move from right to left, the pages still transition from left to right. However, this is minor, and I'm fine with closing this issue.

**Comment by shaunanoordin** [comment]
Hot dang, you're right, I didn't notice the Tutorial "pages" scrolled left to right even when it's in RTL mode... that's mildly confusing.

**Comment by wgranger** [comment]
Yes. It's due to the way flexbox is styled along with the `StepThrough` components. I've tried for a fix, but wasn't successful with my initial attempts and put my efforts elsewhere.
