### ISSUE TITLE
Home page content updates (tbc during internal review)

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#69]
- [x] Explanatory text for "Transcribe Hebrew Fragments" (text with translations [here](https://docs.google.com/document/d/1GbpNxMlqlDX5DSnpENljckRbe-iGl6R-2S_qKvcFMDU/edit?usp=sharing), under "Transcribe Hebrew Script Fragments")

- [x] Explanatory text for "Transcribe Arabic Fragments" (text with translations [here](https://docs.google.com/document/d/1GbpNxMlqlDX5DSnpENljckRbe-iGl6R-2S_qKvcFMDU/edit?usp=sharing), under "Transcribe Arabic Script Fragments")

- [x] Add section heading "Classify Geniza Fragments" + radio button link for Phase 1 

- [x] Add section heading ("Search for Hebrew Keywords" + "Search for Arabic Keywords") + radio button links ("Arabic Keywords" + "Hebrew Keywords") 

- [x] Explanatory text for "Search for Keywords" sections (text with translations [here](https://docs.google.com/document/d/1GbpNxMlqlDX5DSnpENljckRbe-iGl6R-2S_qKvcFMDU/edit#heading=h.9cxn1o2xhu4m) under "Search for Keywords in Hebrew Script Fragments" and "Search for Keywords in Arabic Script Fragments"

FOR FULL LAUNCH:

- [x] Disable both Challenging transcription workflows for ~1 month

- [ ] Banner (?) explaining that Challenging workflows will be available once keyword workflows have generated some subjects

**Comment by wgranger** [comment]
Closing as most items were addressed in #70 and we're forgoing the banner, at least for now.
