### ISSUE TITLE
Add Help Modals

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#97]
Add two new Help Modals to the keyboard:

- [ ] Keyboard script chooser
TEXT: Scroll to choose a different script type for the keyboard. Visit the Script References section in the Crib Sheet for more information.

- [ ] Close keyboard
TEXT: Click here to hide/show the keyboard.

**Comment by snblickhan** [comment]
@beckyrother Following our convo last week, have you had any chance to work on a simple design mock-up for these? No worries if not, just a gentle reminder that we'll be working on this over the next few weeks. Can use placeholder text for the time being. I believe @wgranger and @shaunanoordin thought we may be able to reuse some of the code from the first text modifier, but noted that a design mockup would be useful.

**Comment by beckyrother** [comment]
@snblickhan Thanks for the reminder! It'll be done by Friday.

**Comment by beckyrother** [comment]
The design for this can be found in the invision prototype: https://invis.io/8QL0CFSB6ZH#/295137968_Transcribe-4-5-Transcribe-Info

Thinking about this again, I don't think we need to do one for Toolbar or Subject Info unless we've heard specific feedback that volunteers don't know what "toolbar" or "info" means. I want to give them some benefit of the doubt – all of these elements are non-destructive, so clicking to discover what they are won't break anything. Happy to hear another side of that, however.

**Comment by snblickhan** [comment]
@beckyrother Fair point. It's difficult to know what else to guide on, though -- the feedback we received was that the tutorial is overwhelming, and the request from the research team was basically to help them figure out how to do this, so my approach was "How can we break elements of the tutorial down and add them as reminders?" Suggestions certainly welcome at this point, since the research team didn't request specifics.

**Comment by snblickhan** [comment]
Hmmm. Following the realization that the green help text was never added to the project, I think these 2 new Help Modals + the green instruction pop-ups will suffice.
